name: Task 2 for Toyeeb

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from Toyeeb's GitHub Action!"

      - name: List project files
        run: ls -la
